[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"

# API proxy to Azure backend
[[redirects]]
  from = "/api/*"
  to = "https://scout-analytics-api.azurewebsites.net/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# SPA routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific API URLs
[context.production]
  environment = { VITE_API_URL = "https://scout-analytics-api.azurewebsites.net" }

[context.deploy-preview]
  environment = { VITE_API_URL = "https://scout-analytics-api-preview.azurewebsites.net" }

[context.branch-deploy]
  environment = { VITE_API_URL = "https://scout-analytics-api-preview.azurewebsites.net" }

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"